### ISSUE TITLE
libcrypto.so.1.0.0 no found

### ISSUE THREAD

**Issue by djmott** [alwsl/alwsl#60] opened 2017-04-27 20:16 UTC
Happened to me twice. After installing and updating further pacman use fails with libcrypto.so.1.0.0 not found. After fresh install I used:
pacman -Syuw
rm /etc/ssl/certs/ca-certificates.crt
update-ca-trust
pacman -Su
these went without error but I noticed a warning that pacman was being held back. I noticed libcrypto.so.1.1 is installed so manually created a symlink to it:
ln -sf /usr/lib/libcrypto.so.1.1 /usr/lib/libcrypto.so.1.0.0
pacman -S --force pacman
now pacman works but it concerns me.

**Comment by turbo** [comment] 2017-04-27 22:21
Dupe of https://github.com/alwsl/alwsl/issues/58#issuecomment-297593232

**Closed as completed by turbo** 2017-04-27 22:21 UTC
