### ISSUE TITLE
Error setting certificate verify locations

### ISSUE THREAD

**Issue by yantis** [alwsl/alwsl#55] opened 2017-04-17 00:45 UTC
If you go to upgrade you will get a cert error. The Arch Linux website explains how to fix this error:

![cert](https://cloud.githubusercontent.com/assets/4214239/25075539/d984887e-22cb-11e7-8270-9c7fcff59e5f.PNG)

But that broke it even more:
![cert_errors](https://cloud.githubusercontent.com/assets/4214239/25075565/290e2fda-22cc-11e7-8cc5-406b84f958e2.PNG)

Basically, /etc/ca-certificates/extracted is empty and reinstalling ca-certificates doesn't fix it. The way to fix it is to execute `update-ca-trust`

You might find this link useful:
https://github.com/Antergos/antergos-iso/issues/61

**Comment by nSimonFR** [comment] 2017-04-17 08:46
I think this is a duplicate of #51 ...
The steps to solve it where also already there, and some didn't have to run `update-ca-trust`.

**Comment by turbo** [comment] 2017-04-17 09:30
Closing as upstream issue.

**Closed as completed by turbo** 2017-04-17 09:30 UTC

**Comment by yantis** [comment] 2017-04-17 09:44
As long as you are aware that this does not happen on a non WSL install.  Anyone who does a fresh install this is going to be broken for. The Antergos link above shows the fix they used. I tried several fresh installs on different machines to verify. Though was the windows creator update which may or may not matter. I could easily see someone trying this wonderful tool you made and getting discouraged.

**Comment by turbo** [comment] 2017-04-17 11:51
I'll try to see if I can repackage an updated system this week.

**Comment by pixel-stuck** [comment] 2017-04-21 23:54
since this is still broken, could you leave this issue open until it's solved for good? That way people don't have to look through closed issues for solutions to problems that still exist. If you aren't willing to do that, at least leave a note in the readme or something.

**Comment by ghost** [comment] 2017-04-22 01:39
Just to clarify this for anyone, to fix this (from a completely fresh install, at least) you should follow the [Arch Linux News](https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/) recommendation with one modification, run `update-ca-trust` after `rm /etc/ssl/certs/ca-certificates.crt`:

```
pacman -Syuw 
rm /etc/ssl/certs/ca-certificates.crt
update-ca-trust
pacman -Su
```
 
This issue should probably remain open since you have to do things slightly different from upstream Arch.

**Comment by KyleOndy** [comment] 2017-04-24 10:56
Would it be a good idea to put a note in the `README` about the install procedure so people don't have to come to find this issue?

**Comment by turbo** [comment] 2017-04-24 19:26
Feel free to add one via a PR :)
