### ISSUE TITLE
posix_spawn failed: Operation not permitted

### ISSUE THREAD

**Issue by Rikarin** [alwsl/alwsl#23] opened 2016-10-08 07:16 UTC
Hello,
When I try to compile and then link software through the ldc compiler it thrown me this error:

```
Error: /usr/sbin/ar failed with status: -1
Error: message: posix_spawn failed: Operation not permitted
```

**Comment by turbo** [comment] 2016-10-08 09:15
This is not really helpful on it's own. Please create a self-contained example so I can reproduce this.

**Comment by mati865** [comment] 2016-11-13 14:20
Run as root:

```
touch test.c
clang test.c
```

**Comment by turbo** [comment] 2017-05-31 11:29
Duplicate of #33 .

**Closed as completed by turbo** 2017-05-31 11:29 UTC
Labels: compatibility-request, need-info
